version: '3'
services:
   db: 
     image: mysql:latest
     environment:
       - MYSQL_DATABASE=php_docker
       - MYSQL_USER=php_docker
       - MYSQL_PASSWORD=password # this should live in a env var
       - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
     volumes:
       - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
   www:
     image: php:apache
     volumes:
       - "./:/var/www/html" # sync the current dir on local machine to the dir of container
     ports:
       - 80:80
       - 443:443 # for future ssl traffic
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
       - 8001:80
     environment:
       - PMA_HOST=db
       - PMA_PORT=3306
# *************************************************************************
# version: '3' # docker version
# services:
#    www:
#      image: php:apache #to find image that be using  for this particular service(fullstack web Application)
#      volumes:
#        - "./:/var/www/html" #container and lical host //**sync project dir with container web dir
#      ports:
#        - 80:80
#        - 443:443 #for feature ssl trafic
     
#    db: #db is a service name, it will create an alias to access the database from other services.
#        image: mysql:latest
#        envirement: 
#          - MYSQL_DATABASE=php_docker
#          - MYSQL_USER=php_docker
#          - MYSQL_PASSWORD=password # this should live in a env var
#          - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
#    phpmyadmin:
#       image: phpmyadmin/phpmyadmin
#       ports:
#         - 8001:80
#       environment:
#         - PMA_HOST=db
#         - PMA_PORT=3306  #default value for mysql
# ************************************************************












