
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
           - name: MYSQL_USER
             value: php_docker
           - name: MYSQL_PASSWORD
             value: password
           - name: MYSQL_DATABASE
             value: php_docker