apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: php:7.4-apache
        ports:
        - containerPort: 88
        volumeMounts:
        - name: php-files   # Name of the volume to mount
          mountPath: /var/www/html
      volumes:
      - name: php-files   # Name of the volume
        emptyDir: {}      # Define an empty directory volume
